### ISSUE TITLE
Failed conversion because: plesk-config-troubleshooter, plesk-core and psa-watchdog?

### ISSUE THREAD

**Issue by HHawk** [websavers/centos2alma_openvz#3]
Hi there!

Great work! I am pleased to somebody actually care about users who are running Plesk on Virtuozzo/OpenVZ containers!
However I am getting an error:

> Failed:
> plesk-config-troubleshooter-18.0-2.centos.7+p18.0.61.4+t240527.0733.noarch
> plesk-core-18.0-2.centos.7+p18.0.61.5+t240603.0658.x86_64
> psa-watchdog-18.0-2.centos.7+p18.0.61.4+t240527.0733.x86_64
> 
> Error: Transaction failed
> Error: /usr/share/vzyum/bin/yum failed, exitcode=1
> Failed to upgrade container from 7 to 8 family

Followed by:
> Traceback (most recent call last):
>   File "/root/almaconvert8-plesk", line 827, in <module>
>     args.func()
>   File "/root/almaconvert8-plesk", line 289, in process_cts
>     results = pool.map(process_single_ct, args.CT)
>   File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "/usr/lib64/python3.6/multiprocessing/pool.py", line 638, in get
>     self.wait(timeout)
>   File "/usr/lib64/python3.6/multiprocessing/pool.py", line 635, in wait
>     self._event.wait(timeout)
>   File "/usr/lib64/python3.6/threading.py", line 551, in wait
>     signaled = self._cond.wait(timeout)
>   File "/usr/lib64/python3.6/threading.py", line 295, in wait
>     waiter.acquire()
> KeyboardInterrupt
> Failure running almaconvert8 - Exiting... to resume use --convert and --finish options

I have included the full log of everything, maybe it helps: [full_log.txt](https://github.com/user-attachments/files/15605582/full_log.txt)

Sidenote; I fixed the previous MariaDB error myself, by removing them individually. Error: error: package MariaDB-shared is not installed

Fixed that by using:
>     # Removing MariaDB stuff seperately:
>     vzctl exec $CTID rpm -e MariaDB-compat --nodeps
>     vzctl exec $CTID rpm -e MariaDB-common --nodeps
>     vzctl exec $CTID rpm -e MariaDB-shared --nodeps
>     vzctl exec $CTID rpm -e MariaDB-client --nodeps
>     vzctl exec $CTID rpm -e MariaDB-server --nodeps

Thanks in advance!

Regards,
HHawk

**Comment by HHawk** [comment]
After checking the error log, it seems these issues are/were caused by the fact it couldn't connect to the MySQL service? Which is to be expected as it was removed? Will give it a new go, probably something went wrong. Will restore the snapshot and try again. I will make sure MariaDB is running after the restore.

Edit: same result unfortunately...

**Comment by jas8522** [comment]
You'll see on [line 97 here of the script](https://github.com/websavers/centos2alma_openvz/blob/main/centos2alma_openvz.sh#L97C1-L97C112) that it's supposed to be removing MariaDB at the right point in the process (prior to running the Virtuozzo provided conversion). Did that part not work on your system?

The full log seems to be indicating that there were simply errors in updating Plesk before it actually started the conversion, or am I reading that wrong? Not sure how much I can help with that part, though I wonder if perhaps I should include a plesk version check or something like that to prevent conversion on the wrong version of Plesk.

**Comment by HHawk** [comment]
True, but that didn't work, that's why I used:

# Removing MariaDB stuff seperately:
vzctl exec $CTID rpm -e MariaDB-compat --nodeps
vzctl exec $CTID rpm -e MariaDB-common --nodeps
vzctl exec $CTID rpm -e MariaDB-shared --nodeps
vzctl exec $CTID rpm -e MariaDB-client --nodeps
vzctl exec $CTID rpm -e MariaDB-server --nodeps

I mentioned this. So it should be removed, right?

This (test) Plesk server is running the latest Plesk version along with the latest CentOS 7.x. All updates applied.

Regards

**Comment by jas8522** [comment]
@HHawk the full log only shows the --convert portion. In the --prepare portion this is run:

```
vzctl exec $CTID yum -y remove "plesk-*"
```

Yet in your --convert run, the SQL connection warnings come from the removal of numerous plesk-* packages, including:

```
 plesk-l10n-18.0-2.centos.7+p18.0.61.5+t240603.06
 plesk-config-troubleshooter-18.0-2.centos.7+p18
```

Which should have already been removed by the prepare stage... was the prepare stage not run? If it was run, then the key to resolving this will be determining why the plesk packages weren't removed during the prepare stage like they should have been :)

**Comment by HHawk** [comment]
I will try to give it a new go today, if I have the time. But I already ran it twice (after restoring snapshot though).
I also ran: ./centos2alma_openvz.sh <CTID>

**Comment by jas8522** [comment]
Might not matter now, but I encountered this on a server that had a corrupt / incorrect yum cache contents. I've now included a yum cache clear prior to conversion, so it *should* be fixed.
